#配置选择(dev开发环境  issue发布环境)
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: com.moonce.user.util.DataBaseNamingStrategy #自定义追加table表的方法
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# 日志配置(logback-spring.xml可不写config)
logging:
  config: classpath:config/log/logback-${spring.profiles.active}.xml
jasypt:
  encryptor:
    password: E8167F906E6C55F9A8727C170858DD64
