server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.63.182/mooncedb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ENC(iKrmaqdTQtVTn17dY3ggmvzmIj4tv+T9)

# snowflake生成ID算法配置
snowflake:
  worker-id: 0 # 工作ID (0~31)
  data-center-id: 0 #数据中心ID (0~31)
# 自定义前缀
database:
  prefix: u_